[window]
padding = { x = 12, y = 0 } 

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
size = 18.0                  # Increased default size

[colors.primary]
background = "#2e3440"       # Nord Dark Gray
foreground = "#d8dee9"       # Nord Light Gray

[colors.cursor]
text = "#2e3440"
cursor = "#88c0d0"

[cursor]
style = { shape = "Beam", blinking = "On" }
thickness = 0.2

[colors.normal]
black =   "#3b4252"
red =     "#bf616a"
green =   "#a3be8c"
yellow =  "#ebcb8b"
blue =    "#81a1c1"
magenta = "#b48ead"
cyan =    "#88c0d0"
white =   "#e5e9f0"

[colors.bright]
black =   "#4c566a"
red =     "#bf616a"
green =   "#a3be8c"
yellow =  "#ebcb8b"
blue =    "#81a1c1"
magenta = "#b48ead"
cyan =    "#8fbcbb"
white =   "#eceff4"
