"$schema" = 'https://starship.rs/config-schema.json'

# Prompt format: 
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$fill\
$python\
$line_break$character
"""
# Inserts a blank line between shell prompts
add_newline = true

# Colors
palette = 'catppuccin_mocha'

# Prompt modules 
[username]
show_always = true
style_user = "bold fg:green"
format = '[\[$user]($style)'

[hostname]
ssh_only=false
style = "bold fg:green"
format = '[ @$hostname\] ]($style)'

[directory]
style = "bold fg:blue"
format = "[$path ]($style)"
truncation_length = 6
truncation_symbol = "‚Ä¶/"
truncate_to_repo = false 

[git_branch]
symbol = "Ôêò"
style = "fg:green"
format = '[on](white) [$symbol $branch]($style)'

[git_status]
style = "fg:yellow"
format = ' $ahead_behind \[[$all_status]($style)\]'
ahead ="[ÔÅ¢](fg:blue)"
behind ="[ÔÅ£](fg:peach)"
diverged ="[‚á°${ahead_count}‚á£${behind_count}](bold fg:red)" 
up_to_date="[ÔêÆ](fg:green)"

[fill]
symbol = " "

[python]
symbol = "üêç "
format = '[${symbol}${pyenv_prefix}${version} (\($virtualenv\))]($style)'
style = "yellow bold"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"  


